version: '3'

services:
  protoc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: grpc-sample-server-go
    volumes:
      - ./:/usr/src/app
    ports:
      - '50051:50051'
    tty: true
    stdin_open: true
